# Generated by Django 5.1.5 on 2025-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
