# Generated by Django 3.2 on 2024-05-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_books', to='user.user')),
                ('readers', models.ManyToManyField(related_name='readable_books', to='user.User')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
