# Generated by Django 3.2 on 2024-05-16 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lps', to='user.user')),
            ],
            options={
                'db_table': 'lp',
            },
        ),
    ]
