# Generated by Django 5.1.5 on 2026-01-02 07:37

import utils.primary_key
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=utils.primary_key.generate_secure_short_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('profile_text', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
