# Generated by Django 5.1.5 on 2025-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_text',
            field=models.TextField(blank=True),
        ),
    ]
