# Generated by Django 5.1.5 on 2025-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_profile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
